modLoader="javafml"
loaderVersion="[32,)"
#issueTrackerURL="https://github.com/minecraftabnormals/Upgrade-Aquatic/issues"
#license="https://github.com/minecraftabnormals/Upgrade-Aquatic/blob/master/LICENSE.txt"

[[mods]]
    modId="armor_pieces"
    version="${version}"
    displayName="Armor Pieces"
    credits="Thanks to u/orendorff for most of the ideas"
    authors="possible_triangle"
    description='''Mismatched Armor Pieces and Sets'''

[[dependencies.armor_pieces]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.armor_pieces]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
